[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "team-one"
version = "0.0.1"
description = ''
readme = "readme.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "autogen-core",
    "aiofiles",
    "requests",
    "mammoth",
    "markdownify",
    "numpy",
    "python-pptx",
    "pandas",
    "pdfminer.six",
    "puremagic",
    "binaryornot",
    "pydub",
    "youtube-transcript-api",
    "SpeechRecognition",
    "pathvalidate",
    "playwright",
    "pydantic<3.0.0,>=2.0.0",
]

[project.optional-dependencies]
ocr = [
    "easyocr",
    "torchvision>=0.12",
]

[tool.uv]
dev-dependencies = [
    "aiofiles",
    "types-aiofiles",
    "types-requests",
    "types-pillow",
    "azure-identity",
    "openpyxl",
]


[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
test.sequence = [
    "playwright install",
    "pytest -n auto",
]
test.default_item_type = "cmd"

[tool.ruff]
extend = "../../pyproject.toml"
exclude = ["build", "dist", "page_script.js"]
include = [
    "src/**",
    "examples/*.py",
    "tests/**/*.py",
]


[tool.pyright]
extend = "../../pyproject.toml"
include = ["src", "tests", "examples"]